name: Deploy PHP Theme to WP Engine
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Theme to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_ENV: 'adytoninvesdev' 
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSH_KEY_PRIVATE }}
          SRC_PATH: './' 
          REMOTE_PATH: 'wp-content/themes/adyton-resources/' 
          # ADD THIS LINE: It forces the server to delete orphaned files
          FLAGS: -azvr --inplace --delete --exclude=.*